version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: "./start-server.sh"
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
    env_file: ./backend/.env
    stdin_open: true
    tty: true
    environment:
      DATABASE_HOST: db
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
